name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pixelcmtd/markdown-doctest-action@master
        with:
          compiler: clang
